"use client"
import React from 'react'
import MainTable from '../Tables/MainTable';

const columns = [
  {
    title: 'Name',
    dataIndex: 'name',
    showSorterTooltip: {
      target: 'full-header',
    },
    filters: [
      {
        text: 'Joe',
        value: 'Joe',
      },
      {
        text: 'Jim',
        value: 'Jim',
      },
      {
        text: 'Submenu',
        value: 'Submenu',
        children: [
          {
            text: 'Green',
            value: 'Green',
          },
          {
            text: 'Black',
            value: 'Black',
          },
        ],
      },
    ],
    onFilter: (value, record) => record.name.indexOf(value) === 0,
    sorter: (a, b) => a.name.length - b.name.length,
    sortDirections: ['descend'],
  },
  {
    title: 'Age',
    dataIndex: 'age',
    defaultSortOrder: 'descend',
    sorter: (a, b) => a.age - b.age,
  },
  {
    title: 'Address',
    dataIndex: 'address',
    filters: [
      {
        text: 'London',
        value: 'London',
      },
      {
        text: 'New York',
        value: 'New York',
      },
    ],
    onFilter: (value, record) => record.address.indexOf(value) === 0,
  },
];
const data = [
  { key: '1', name: 'John Brown', age: 32, address: 'New York No. 1 Lake Park' },
  { key: '2', name: 'Jim Green', age: 42, address: 'London No. 1 Lake Park' },
  { key: '3', name: 'Joe Black', age: 32, address: 'Sydney No. 1 Lake Park' },
  { key: '4', name: 'Jim Red', age: 32, address: 'London No. 2 Lake Park' },
  { key: '5', name: 'Sarah White', age: 28, address: 'Tokyo No. 1 Hill Park' },
  { key: '6', name: 'Michael Blue', age: 36, address: 'Paris No. 1 River Park' },
  { key: '7', name: 'Nancy Yellow', age: 25, address: 'Berlin No. 1 Street' },
  { key: '8', name: 'Chris Brown', age: 30, address: 'Madrid No. 1 Plaza' },
  { key: '9', name: 'Olivia Green', age: 40, address: 'Rome No. 1 Circle' },
  { key: '10', name: 'James Black', age: 35, address: 'Lisbon No. 1 Square' },
  { key: '11', name: 'Emily White', age: 27, address: 'Vienna No. 2 Street' },
  { key: '12', name: 'David Blue', age: 33, address: 'Zurich No. 1 Hill Park' },
  { key: '13', name: 'Sophia Yellow', age: 22, address: 'Copenhagen No. 3 Plaza' },
  { key: '14', name: 'Lucas Brown', age: 29, address: 'Amsterdam No. 2 Circle' },
  { key: '15', name: 'Mia Green', age: 26, address: 'Brussels No. 4 Street' },
  { key: '16', name: 'Liam Black', age: 31, address: 'Stockholm No. 2 Plaza' },
  { key: '17', name: 'Emma White', age: 24, address: 'Oslo No. 1 Park' },
  { key: '18', name: 'Noah Blue', age: 34, address: 'Helsinki No. 3 Circle' },
  { key: '19', name: 'Isabella Yellow', age: 28, address: 'Dublin No. 2 Square' },
  { key: '20', name: 'Ethan Brown', age: 32, address: 'Warsaw No. 4 Park' },
  { key: '21', name: 'Ava Green', age: 30, address: 'Prague No. 1 Hill' },
  { key: '22', name: 'Mason Black', age: 35, address: 'Budapest No. 3 Street' },
  { key: '23', name: 'Charlotte White', age: 33, address: 'Bratislava No. 2 Plaza' },
  { key: '24', name: 'Elijah Blue', age: 27, address: 'Ljubljana No. 1 Circle' },
  { key: '25', name: 'Amelia Yellow', age: 29, address: 'Tallinn No. 3 Park' },
  { key: '26', name: 'Logan Brown', age: 31, address: 'Vilnius No. 1 Street' },
  { key: '27', name: 'Abigail Green', age: 25, address: 'Riga No. 4 Plaza' },
  { key: '28', name: 'Lucas Black', age: 28, address: 'Sofia No. 1 Circle' },
  { key: '29', name: 'Harper White', age: 32, address: 'Athens No. 3 Hill' },
  { key: '30', name: 'Aiden Blue', age: 26, address: 'Belgrade No. 2 Park' },
  { key: '31', name: 'Grace Yellow', age: 34, address: 'Zagreb No. 1 Square' },
  { key: '32', name: 'Henry Brown', age: 37, address: 'Sarajevo No. 2 Street' },
  { key: '33', name: 'Lily Green', age: 29, address: 'Podgorica No. 3 Plaza' },
  { key: '34', name: 'Sebastian Black', age: 33, address: 'Skopje No. 4 Circle' },
  { key: '35', name: 'Chloe White', age: 28, address: 'Tirana No. 1 Hill' },
  { key: '36', name: 'Daniel Blue', age: 31, address: 'Pristina No. 3 Park' },
  { key: '37', name: 'Eleanor Yellow', age: 35, address: 'Bucharest No. 2 Street' },
  { key: '38', name: 'Matthew Brown', age: 34, address: 'Kiev No. 1 Plaza' },
  { key: '39', name: 'Victoria Green', age: 27, address: 'Minsk No. 4 Circle' },
  { key: '40', name: 'Samuel Black', age: 32, address: 'Chisinau No. 2 Square' },
  { key: '41', name: 'Sofia White', age: 24, address: 'Tbilisi No. 3 Hill' },
  { key: '42', name: 'Jack Blue', age: 29, address: 'Yerevan No. 1 Park' },
  { key: '43', name: 'Penelope Yellow', age: 30, address: 'Baku No. 4 Street' },
  { key: '44', name: 'Alexander Brown', age: 36, address: 'Ankara No. 2 Plaza' },
  { key: '45', name: 'Zoey Green', age: 25, address: 'Istanbul No. 3 Circle' },
  { key: '46', name: 'Owen Black', age: 31, address: 'Tehran No. 4 Hill' },
  { key: '47', name: 'Madison White', age: 28, address: 'Baghdad No. 1 Park' },
  { key: '48', name: 'Wyatt Blue', age: 34, address: 'Damascus No. 2 Street' },
  { key: '49', name: 'Scarlett Yellow', age: 26, address: 'Amman No. 3 Plaza' },
  { key: '50', name: 'John Brown', age: 32, address: 'Riyadh No. 1 Circle' },
  { key: '51', name: 'Avery Green', age: 31, address: 'Doha No. 4 Square' },
  { key: '52', name: 'James Black', age: 35, address: 'Abu Dhabi No. 2 Hill' },
  { key: '53', name: 'Luna White', age: 27, address: 'Dubai No. 3 Park' },
  { key: '54', name: 'Sebastian Blue', age: 33, address: 'Muscat No. 1 Street' },
  { key: '55', name: 'Emily Yellow', age: 29, address: 'Manama No. 4 Plaza' },
  { key: '56', name: 'Joseph Brown', age: 28, address: 'Kuwait No. 1 Circle' },
  { key: '57', name: 'Layla Green', age: 32, address: 'Cairo No. 2 Square' },
  { key: '58', name: 'Benjamin Black', age: 30, address: 'Algiers No. 3 Hill' },
  { key: '59', name: 'Sofia White', age: 24, address: 'Tunis No. 4 Park' },
  { key: '60', name: 'Lucas Blue', age: 34, address: 'Rabat No. 1 Street' },
  { key: '61', name: 'Zoey Yellow', age: 25, address: 'Casablanca No. 2 Plaza' },
  { key: '62', name: 'Jackson Brown', age: 31, address: 'Dakar No. 3 Circle' },
  { key: '63', name: 'Amelia Green', age: 26, address: 'Accra No. 4 Hill' },
  { key: '64', name: 'Logan Black', age: 32, address: 'Lagos No. 1 Park' },
  { key: '65', name: 'Grace White', age: 30, address: 'Nairobi No. 2 Street' },
  { key: '66', name: 'Aiden Blue', age: 34, address: 'Addis Ababa No. 3 Plaza' },
  { key: '67', name: 'Isabella Yellow', age: 28, address: 'Kampala No. 4 Circle' },
  { key: '68', name: 'Ethan Brown', age: 27, address: 'Khartoum No. 1 Hill' },
  { key: '69', name: 'Mia Green', age: 25, address: 'Harare No. 2 Park' },
  { key: '70', name: 'Noah Black', age: 33, address: 'Lusaka No. 3 Street' },
  { key: '71', name: 'Sophia White', age: 29, address: 'Maputo No. 4 Plaza' },
  { key: '72', name: 'Liam Blue', age: 31, address: 'Cape Town No. 1 Circle' },
  { key: '73', name: 'Charlotte Yellow', age: 30, address: 'Pretoria No. 2 Hill' },
  { key: '74', name: 'Mason Brown', age: 32, address: 'Johannesburg No. 3 Park' },
  { key: '75', name: 'Harper Green', age: 28, address: 'Windhoek No. 4 Street' },
  { key: '76', name: 'Ella Black', age: 26, address: 'Gaborone No. 1 Plaza' },
  { key: '77', name: 'William White', age: 35, address: 'Luanda No. 2 Circle' },
  { key: '78', name: 'Avery Blue', age: 29, address: 'Kinshasa No. 3 Hill' },
  { key: '79', name: 'Eleanor Yellow', age: 31, address: 'Brazzaville No. 4 Park' },
  { key: '80', name: 'Henry Brown', age: 36, address: 'Libreville No. 1 Street' },
  { key: '81', name: 'Abigail Green', age: 27, address: 'Yaoundé No. 2 Plaza' },
  { key: '82', name: 'Logan Black', age: 33, address: 'Douala No. 3 Circle' },
  { key: '83', name: 'Ethan White', age: 32, address: 'Bangui No. 4 Hill' },
  { key: '84', name: 'Amelia Blue', age: 24, address: 'Kigali No. 1 Park' },
  { key: '85', name: 'Madison Yellow', age: 30, address: 'Bujumbura No. 2 Street' },
  { key: '86', name: 'Jackson Brown', age: 34, address: 'NDjamena No. 3 Plaza' },
  { key: '87', name: 'Victoria Green', age: 28, address: 'Niamey No. 4 Circle' },
  { key: '88', name: 'Oliver Black', age: 27, address: 'Ouagadougou No. 1 Hill' },
  { key: '89', name: 'Lily White', age: 26, address: 'Bamako No. 2 Park' },
  { key: '90', name: 'Jacob Blue', age: 31, address: 'Freetown No. 3 Street' },
  { key: '91', name: 'Emily Yellow', age: 29, address: 'Monrovia No. 4 Plaza' },
  { key: '92', name: 'James Brown', age: 33, address: 'Abidjan No. 1 Circle' },
  { key: '93', name: 'Benjamin Green', age: 32, address: 'Yamoussoukro No. 2 Hill' },
  { key: '94', name: 'Sophia Black', age: 25, address: 'Lome No. 3 Park' },
  { key: '95', name: 'Evelyn White', age: 27, address: 'Cotonou No. 4 Street' },
  { key: '96', name: 'Alexander Blue', age: 30, address: 'Porto-Novo No. 1 Plaza' },
  { key: '97', name: 'Luna Yellow', age: 26, address: 'Lagos No. 2 Circle' },
  { key: '98', name: 'Sebastian Brown', age: 34, address: 'Kano No. 3 Hill' },
  { key: '99', name: 'Sofia Green', age: 24, address: 'Ibadan No. 4 Park' },
  { key: '100', name: 'Jackson Black', age: 32, address: 'Abuja No. 1 Street' },
];
export default function AcountpayabalereceivableTable() {
  return (
    <div>
      <MainTable columns={columns} data={data}/>
    </div>
  )
}
