import { Button } from "antd";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <Button type="primary">Button</Button>
      
    </div>
  );
}
